spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orderdb
    username: user1
    password: '0000'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8083